### ISSUE TITLE
貌似支持https了

### ISSUE THREAD

**Issue by Marukon** [chajianku/wmzz_static_cdn#1]
array(
			'https://apps.bdimg.com/libs/jquery/1.9.1/jquery.min.js',
			'https://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap.min.css',
			'https://apps.bdimg.com/libs/bootstrap/3.3.0/js/bootstrap.min.js',
			'https://apps.bdimg.com/libs/todc-bootstrap/3.1.1-3.2.1/todc-bootstrap.min.css'
		), $str);
}

测试了一下改成这样，也可以的。望作者测试更新，谢谢！

**Comment by Marukon** [comment]
就是更新了https支持。

**Comment by chajianku** [comment]
感谢提交反馈。
